### ISSUE TITLE
Number of training steps for each dataset

### ISSUE THREAD

**Issue by alexlioralexli** [louaaron/Score-Entropy-Discrete-Diffusion#6]
I'm trying to reproduce the results in the paper, and it's not clear how many training iterations or epochs were done for each dataset. The default number of steps appears to be 1,300,001, but this is way too high. Could you clarify the right number for text8, 1BW, and OpenWebText?

**Comment by louaaron** [comment]
Hi Alex,

OpenWebText was trained on 400k iterations, text8 and 1bw were trained for one million following the D3PM paper.

**Comment by dingfangyu** [comment]
> Hi Alex,
> 
> OpenWebText was trained on 400k iterations, text8 and 1bw were trained for one million following the D3PM paper.

Hi Aaron, 
Are the open-sourced model checkpoints on hugging face trained for 400k steps on openwebtext?
